const dishes = [
    {
      keyword: "gazpacho",
      name: "Гаспачо",
      price: 195,
      category: "soup",
      weight: "350 г",
      image: "menu/soups/gazpacho.jpg",
    },
    {
      keyword: "mushroom_soup",
      name: "Грибной суп-пюре",
      price: 185,
      category: "soup",
      weight: "330 г",
      image: "menu/soups/mushroom_soup.jpg",
    },
    {
      keyword: "norwegian_soup",
      name: "Норвежский суп",
      price: 270,
      category: "soup",
      weight: "330 г",
      image: "menu/soups/norwegian_soup.jpg",
    },
    {
      keyword: "chicken_cutlets",
      name: "Котлеты из курицы с картофельным пюре",
      price: 225,
      category: "main",
      weight: "280 г",
      image: "menu/main_course/chickencutletsandmashedpotatoes.jpg",
    },
    {
      keyword: "fried_potatoes",
      name: "Жареная картошка с грибами",
      price: 150,
      category: "main",
      weight: "250 г",
      image: "menu/main_course/friedpotatoeswithmushrooms1.jpg",
    },
    {
      keyword: "lasagna",
      name: "Лазанья",
      price: 385,
      category: "main",
      weight: "310 г",
      image: "menu/main_course/lasagna.jpg",
    },
    {
      keyword: "apple_juice",
      name: "Яблочный сок",
      price: 90,
      category: "beverages",
      weight: "300 мл",
      image: "menu/beverages/applejuice.jpg",
    },
    {
      keyword: "carrot_juice",
      name: "Морковный сок",
      price: 110,
      category: "beverages",
      weight: "300 мл",
      image: "menu/beverages/carrotjuice.jpg",
    },
    {
      keyword: "orange_juice",
      name: "Апельсиновый сок",
      price: 120,
      category: "beverages",
      weight: "300 мл",
      image: "menu/beverages/orangejuice.jpg",
    },
  ];
  